#各个地方的变量意思不同，请注意看注解

数据:
  地址: //localhost:3306/RUNOOB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  用户名: root
  密码:

#[1]代表排名
#[2]代表玩家
#[3]代表充值总数
全息显示:
  #标题不能使用变量
  排行榜刷新时间: 3600
  排行标题: "&6点卷充值榜"
  排行消息: "&a[1].[2] => [3]"
  世界: "world"
  x: 0
  y: 0
  z: 0



#[1]代表的是使用的玩家名称
#[2]代表的是当前充值的点卷总量
#[3]代表的是还差多少领礼包
消息:
  金额不足消息: "&4领取失败,金额不足 您当前充值了[2] 还缺[3] 才可以领取礼包"
  已被领取消息: "&4领取失败,已被领取"
  领取成功消息: "&b已将奖励发放给至你的背包"
  奖励不存在消息: "&4当前领取的礼包不存在"
  玩家不存在消息: "&4当前玩家不存在"


#[1]代表的是使用的玩家名称
#礼包名请勿重复 否则将发生错误
#礼包1:
#  金额限制: 100
#  礼包内容:
#    - [指令]
#    - [指令]
#    - ....
礼包详情:
  充值大礼包:
    金额限制: 100
    礼包内容:
      - op [1]
      - msg [1] 这是第二条
      - msg [1] 这是第三条
      - msg [1] 这是第四条